name: Earn Pair Extraordinaire Badge

on:
  workflow_dispatch:  # Allows for manual triggering of the workflow

jobs:
  create_coauthored_commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install PyGithub
        run: |
          python -m pip install --upgrade pip
          pip install PyGithub

      - name: Run Script to Create Co-authored Commit
        env:
          KING6: ${{ secrets.KING6 }}  # GitHub token stored as a repository secret
        run: |
          echo "
          from github import Github
          import os

          # GitHub Personal Access Token (PAT)
          GITHUB_TOKEN = os.getenv('KING6')
          GITHUB_USERNAME = 'ums91'

          # Authenticate with GitHub
          g = Github(GITHUB_TOKEN)

          # Function to co-author a commit for 'Pair Extraordinaire' badge
          def create_coauthored_commit(repo_name):
              try:
                  repo = g.get_repo(repo_name)
                  commit_message = (
                      'Automated commit for Pair Extraordinaire achievement\\n\\n'
                      'Co-authored-by: ums91 <omargoroo91@gmail.com>\\n'
                      'Co-authored-by: learnwithums <learnwithums@gmail.com>'
                  )
                  repo.create_file(
                      path='achievement_commit.md',  # File to be created
                      message=commit_message,        # Commit message with co-authors
                      content='This is a co-authored commit to achieve the Pair Extraordinaire badge.',  # File content
                  )
                  print('Co-authored commit created.')
              except Exception as e:
                  print(f'Failed to create co-authored commit: {e}')

          # Run the function to earn 'Pair Extraordinaire'
          create_coauthored_commit('learnwithums/test1')
          " > coauthored_commit.py
          
          python coauthored_commit.py
